### ISSUE TITLE
Add recommended instructions to format the log's output 

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-core#108]
### Expected behavior

Readme suggests a recommend way to read the logs. For example `npm start | npx bunyan -o short`

### Actual behavior

Readme doesn't recommend any way to format the JSON logs.

### Steps to reproduce

`npm start`

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0+`

**Comment by Tschakki** [comment]
I aggree, and we should use `node dist/index.js` instead of `npm start` now in our documentation files. 😉
