### ISSUE TITLE
Partial custom config migration during node upgrade

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#116]
### Expected behavior
When a node is upgraded all the custom config should be migrated and ones which are not supported should be shown as `warning` or `info`.

**Note: Node upgrade has a recurring issue with one or the other config fields, this time while we fix the issue, whoever is working on it and approving the PR please make sure to add tests by scenario or whichever is convenient, but the tests should cover all possible scenarios to avoid such recurring issues, Danke!.**

### Actual behavior
Upgrading a node with version `2.0.0` to `2.0.x` does not migrate some of the custom config fields like `logger` under `components`.
### Steps to reproduce
- Deploy 2.0.0 node
- Create a custom config(2.0.0 node) with
```
{
	"components": {
		"logger": {
			"fileLogLevel": "info"
		}
	}
}
```
- Upgrade to `2.0.1` version
- Observe the `config.json`, it will not include the custom `logger` config
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.1, Binary release

**Comment by michielmulders** [comment]
@ManuGowda We tested the upgrade config for the latest using your custom config.
We believe it is correct behavior as `fileLogLevel: info` is the default, and so, gets removed.
We only create the output with custom values.

`node scripts/update_config.js -n testnet -o new-config.json local.config.json 2.0.0`
```
{
	"components": {
		"logger": {
			"fileLogLevel": "info"
		}
	}
}
```

Danke!

**Comment by michielmulders** [comment]
If you try with:

```
{
	"components": {
		"logger": {
			"fileLogLevel": "info",
                         "consoleLogLevel": "debug"
		}
	}
}
```

Will generate:
```
{
	"components": {
		"logger": {
			"consoleLogLevel": "debug"
		}
	}
}
```

**Comment by ManuGowda** [comment]
@michielmulders, as we discussed, the custom config should always retain the config even if they are present as part of the default config otherwise, it defeats the whole purpose of having custom config. The users should be allowed to retain all the custom config supported fields so that they can use it according to his needs without bothering about default or network config.

**Comment by michielmulders** [comment]
For now, I've added tests and updated some of the config migrations which were incorrect.
After a discussion with Shu, we decided to keep the behavior til 3.0 before changing/modifying this.
