### ISSUE TITLE
Need strategy for detecting config changes

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-core#124]
### Expected behavior
Currently, we have updated the tests as integrations tests for `update_config` script.
However, this script does not fail when new config changes are added.
It only tracks if something goes wrong with the current covered config.

First of all, we need a Jenkins job that runs those tests.
But more importantly, we should come up with a strategy that fails the tests whenever you add a new property without modifying the integration tests. E.g. check if the full config is the same as the fixture config.

Referring to the [previous comment in `update_config` issue](https://github.com/LiskHQ/lisk-core/pull/117#issuecomment-520782481).

### Which version(s) does this affect? (Environment, OS, etc...)
2.0+

**Comment by ManuGowda** [comment]
Closing this issue as we no longer have the `update_config` strategy.
