### ISSUE TITLE
Proposal for Collaboration on Improving SocketCluster

### ISSUE THREAD

**Issue by faustbrian** [LiskHQ/lisk-core#134]
Hi,

Recently there have been several bug reports for SocketCluster that resulted in security vulnerabilities for LISK, ARK and a few others that use the project. As those reports came in quick succession we anticipate more bugs and odd behaviours observed with how SocketCluster handles things.

With this in mind, we’d like to propose that we collaborate on SocketCluster in relation to where we both use it, in blockchain applications. This would enable both of us to take advantage of benefits such as better performance, helpful features and more deterministic behaviour for developers. Unexpected behaviours like reported in https://github.com/SocketCluster/socketcluster/issues/506 could throw off a developer, causing unforeseen delays and inefficiencies to a project, something which we hope you agree would be in both our interests to avoid.

As a starting point we would like to propose that we both allocate developer resources and time to get more in-depth knowledge about how SocketCluster works to make meaningful contributions. This hopefully will result in more improvements, bugs found and less security vulnerabilities on the P2P communication layer for projects that rely on SocketCluster.

Secondly we would want to open a direct communication channel so that collaboration becomes easier and discussions can be had about issues experienced with SocketCluster, how to approach them and figure out a solution together. This should result in a knowledge exchange on both sides which will hopefully lead to better and more efficient solutions.

As we all work on blockchain based projects we know what can happen to a network if the P2P communication layer has bugs that can hinder communication or require workarounds and as the number of workarounds and patches grows a lot of unnecessary code and technical debt piles up over time.

In summary, we hope that we can come together on this and work in partnership on to improve SocketCluster so that everyone can harvest the benefits and focus on building out their applications. Please feel free to share your thoughts on this proposal.

_We posted this proposal on the Lisk Core repository (instead of SocketCluster) as we're interested in opening up a direct dialogue with Lisk in order to collaborate. Given that the maintainer @jondubois also works for Lisk, we hoped that this would be the most effective approach._

**Comment by jondubois** [comment]
@faustbrian Don't hesitate to also raise specific issues on the SocketCluster repo if you have issues.

The ping/pong behaviour which you referenced in your post is not an issue for the majority of SC use cases (e.g. when the client is running on a front end). I understand that some of the quicks of SC need adjustment to handle P2P use cases better (I've already had to add new config properties in the past to optimise it better for P2P) so feel free to raise specific issues on the SC repo. I'm very interested to keep improving support for P2P use cases where the client is running on the server side.

**Comment by faustbrian** [comment]
@jondubois Thanks for the reply.

I've been looking at Asyngular for some time now and been wondering when it would become the main focus and replace SocketCluster as it would make a lot of code obsolete. clean things up and make contributing a lot easier.

Do you have an ETA for when you want to merge Asyngular into SocketCluster? If I would know a rough ETA I could allocate some resources to Asyngular instead of inspecting SocketCluster and ending up with wasted time as the efforts get undone as soon as Asyngular gets merged.

Nevertheless, I'll start to gather some feedback from our developers and open an issue on SocketCluster once I have it ready so that we can talk about potential issues and improvements there.

**Comment by shuse2** [comment]
Since the discussion move to SocketCluster, we are closing this issue
