### ISSUE TITLE
Node keeps restarting randomly

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-core#146]
### Expected behavior

My Lisk node should not restart itself automatically.

### Actual behavior

My Testnet node restarts itself automatically every few hours/days.
This causes the forging to stop, which is very annoying.

### Steps to reproduce
Server: Digital Ocean Droplet, 2GB RAM
Lisk Core dist: Binary

- Start node and enable forging
- Wait until red in Explorer

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core 2.1.3-rc.1

**Comment by ManuGowda** [comment]
Closing this issue as the `2.1.4` patch release stabilizes the node and network.
