### ISSUE TITLE
Test DApp registration transaction disable

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#19]
### Expected behavior

- [x] Alphanet(2.0.0) should not accept any DApp registration from height `0`
- [x] Testnet(2.0.0) Set height for DApp disabling refer [here](https://github.com/LiskHQ/lisk-sdk/issues/3492) Testnet(2.0.0) for setting height @lsilvs should be able to help here. After setting the height send DApp transaction for following scenarios
         - send dapp transaction less than `disable height`
         - send dapp transaction equal to `disable height`
         - send dapp transaction greater than `disable height`
- [x] Mainnet(2.0.0) Set height for DApp disabling refer [here](https://github.com/LiskHQ/lisk-sdk/issues/3492) Testnet(2.0.0) for setting height @lsilvs should be able to help here. After setting the height send DApp transaction for following scenarios
         - send dapp transaction less than `disable height`
         - send dapp transaction equal to `disable height`
         - send dapp transaction greater than `disable height`

**Comment by limiaspasdaniel** [comment]
All working as it should on Alphanet, Testnet and Mainnet on the described scenarios.
