### ISSUE TITLE
Inconsistency between config.json and PostgreSQL behaviour

### ISSUE THREAD

**Issue by friday-james** [LiskHQ/lisk-core#190]
### Expected behavior
By defining `components.storage.port` in "config.json", PostgreSQL should start at the defined port.

### Actual behavior
After defining the port in `config.json`,  Then execute `bash lisk.sh start_db`, PostgreSQL still start according to configurations in "$PWD/pgsql/data", which is confusing.

### Steps to reproduce
Define `components.storage.port` in "config.json as a new port number, e.g. "5533". Then run `bash lisk.sh start_db`. PostgreSQL will fail to start.

### Which version(s) does this affect? (Environment, OS, etc...)
Ubuntu 18.04.3 LTS

### Suggested change
It is not suggested to change the PostgreSQL config file, nor overriding the PostgreSQL config by definitions in "config.json". As users may change the "config.json" after starting PostgreSQL, doing do will make `stop_postgresql()` fails to execute.
Hence it is suggested to check the consistency of two config files: "config.json" and "$PWD/pgsql/data/postgresql.conf ". Then tell the user when there is inconsistency, and tell them "config.json" is responsible for the lisk processes to find the db port, while "$PWD/pgsql/data/postgresql.conf " is responsible for the definition of PostgreSQL's port.

i.e. adding a function to check consistency between two config files, and output an error message in `start_postgresql()` and `stop_postgresql()`.

P.S. I can help to edit the code. :)

**Comment by shuse2** [comment]
Closing this in favor of https://github.com/LiskHQ/lisk-sdk/issues/5238
