### ISSUE TITLE
Lisk core 2.1.4 docker exited with code 139

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#202]
### Expected behavior
The docker image should start the Lisk core without crashing
### Actual behavior
Lisk 2.1.4 Docker image 
https://hub.docker.com/layers/lisk/core/2.1.4/images/sha256-775b2c19a1344d2262702367a5fb2be9d80e839404f8db85eff86539825fd710

I installed lisk-core 2.1.4 Docker image from Dockerhub,
and run docker-compose up, but it exited with code 139.

this is error message, 

```
lisk_1  | timeout: unrecognized option: t
lisk_1  | BusyBox v1.31.1 () multi-call binary.
lisk_1  |
lisk_1  | Usage: timeout [-s SIG] SECS PROG ARGS
lisk_1  |
lisk_1  | Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
lisk_1  | Default SIG: TERM.
lisk_1  | wait-for-it.sh: timeout occurred after waiting 15 seconds for db:5432
lisk_docker_task_1 exited with code 0
lisk_docker_lisk_1 exited with code 139
```

it seems to errors caused by wait-for-it.sh 
### Steps to reproduce
- Pull the latest docker image 
- Run lisk core docker
### Which version(s) does this affect? (Environment, OS, etc...)
2.1.4

**Comment by fchavant** [comment]
`wait-for-it.sh` failing with (newer version of?) `busybox`'s `timeout` only hides the real error (`lisk_docker_lisk_1 exited with code 139`, a segmentation fault) which happens with musl (alpine) and recent seccomp filters (linux); @Nazgolze is investigating this.

As a workaround we can switch to the `node:10` base image at the cost of larger images.

**Comment by Nazgolze** [comment]
Haven't found all of the answers yet, but the offending syscall is `membarrier`
