### ISSUE TITLE
Create command to export/import forger_info

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-core#208]
### Expected behavior
lisk script should have a way to export and import the `forger_info` table, and import back to the `forger_info`
It should not touch any other tables

### Actual behavior
It doesn't exist now.

### Which version(s) does this affect? (Environment, OS, etc...)
It should target `release/3.0.0`

**Comment by fchavant** [comment]
@shuse2 do we want the output file to contain the height? a timestamp maybe?

**Comment by shuse2** [comment]
@fchavant timestamp would be nice to differentiate files (if there are multiple

**Comment by fchavant** [comment]
@shuse2 OK then here is my suggestion:
- `forger_backup.sh` dumps `forger_info` to file `backups/forger_info-<timestamp>.sql`
- `forger_restore.sh <FILE>` restores to `forger_info` table

e.g.:

```
~> ./forger_backup.sh
Created /home/lisk/lisk-test/backups/forger_info-1580224749.sql
~> ./forger_restore.sh backups/forger_info-1580224749.sql
```
