### ISSUE TITLE
Create reclaim transaction command

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#256]
### Description
- Create reclaim transaction creation command.
- `transaction:create -t 16` or `transaction:create:reclaim` should take `amount` and `address`
`transaction:create -t 16 fee nonce amount address`

### Motivation
With the new reclaim transaction, reclaim transaction command is required to create transaction

### Acceptance Criteria
- Write description and examples.
- Test both `transaction:create -t 16` and `transaction:create:reclaim` cases

### Additional information
Related issues: LiskHQ/lisk-sdk#5167

**Comment by shuse2** [comment]
Create transaction command is generic now that it does not need specific command
