### ISSUE TITLE
Add core blockchain:hash command

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-core#265]
### Description

Add `blockchain:hash` command to show a hash of the blockchain stored in the data path, according to the following specification:

1. It should show an error if the application is running
2. It should create tarball with `blockchain.db` and hash
3. It should support:

```
--data-path (-d / LISK_DATA_PATH)
  Specifies which data path the application should use
```

If database is in use, it should show the error.

### Motivation

Allow blockchain data to be verified according to a displayed hash.

### Acceptance Criteria

- Add unit tests
- Examples and description are clear and correct
- Creating some blockchain, and wait for height 500, and sync with the node with another node. Run this command for both of the node, and it should result in the same hash

### Additional Information

Related issues: #254

**Comment by nazarhussain** [comment]
The content of binary files are differ, so we can't create tarball to hash one file. We have to read the whole db content manually to generate deterministic hash. 

```
❯ diff -s ~/.lisk/default/data/blockchain.db/ ~/.lisk/default2/data/blockchain.db/
Binary files ~/.lisk/default/data/blockchain.db/000003.log and ~/.lisk/default2/data/blockchain.db/000003.log differ
Files ~/.lisk/default/data/blockchain.db/CURRENT and ~/.lisk/default2/data/blockchain.db/CURRENT are identical
diff -s ~/.lisk/default/data/blockchain.db/IDENTITY ~/.lisk/default2/data/blockchain.db/IDENTITY
1c1
< 1624aeee6fdd0601-68ab381bc53b5742
\ No newline at end of file
---
> 1624aee99332c111-11e3e07c573f7dbd
\ No newline at end of file
Files ~/.lisk/default/data/blockchain.db/LOCK and ~/.lisk/default2/data/blockchain.db/LOCK are identical
Files ~/.lisk/default/data/blockchain.db/MANIFEST-000001 and ~/.lisk/default2/data/blockchain.db/MANIFEST-000001 are identical
diff -s ~/.lisk/default/data/blockchain.db/OPTIONS-000005 ~/.lisk/default2/data/blockchain.db/OPTIONS-000005
26c26
<   wal_dir=~/.lisk/default/data/blockchain.db
---
>   wal_dir=~/.lisk/default2/data/blockchain.db
```
