### ISSUE TITLE
Set block height to disable Dapp Transaction on testnet

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-core#29]
### Expected behavior
Expect to define a block height to disable Dapp Transaction on testnet

The property `modules.chain.exceptions.precedent.disableDappTransaction` should be added to the testnet config file with the block height.

Config file: `config/testnet/config.json`

### Which version(s) does this affect? (Environment, OS, etc...)
`release/2.0.0`

**Comment by 4miners** [comment]
Done in https://github.com/LiskHQ/lisk-core/pull/86
