### ISSUE TITLE
Use lisk-sdk instead of lisk-framework

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-core#37]
### Expected behavior
Use `lisk-sdk` depencency.
### Actual behavior
Use `lisk-framework` depencency.

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0`

**Comment by 4miners** [comment]
This is already done https://github.com/LiskHQ/lisk-core/commit/148b37b5eef413466d5eff2168c3d6d959ef2faa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
