### ISSUE TITLE
Improve command line description and flag naming and description

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#371]
### Description

The core CLI commands `description` and `flag` description of grammar needs to be corrected.

### Motivation

The core CLI commands will be interfaced with developers and users, for better understanding of commands the grammar needs to be corrected.

Revisit all the core CLI commands and fix the grammar.

### Acceptance Criteria

- Update Root and sub root commands `description` with better grammar
- Update flags and its description with better grammar

### Additional Information
Example
Actual
```
blockchain:download  Download blockchain data from a provided snapshot.
blockchain:export    Export blockchain data for given data path
blockchain:hash      Generate hash for blockchain data for given data path
blockchain:import    Import blockchain data for given data path
blockchain:reset     Resets the blockchain data.
```
Improved version
```
blockchain:download  Download from <URL>.
blockchain:export    Export to <FILE>
blockchain:import    Import from <FILE>
```

**Comment by pablitovicente** [comment]
`--enable-forger` which is for enabling the forger plugin should be renamed as it could be confused as a flag for enabling forging

**Comment by ManuGowda** [comment]
After downloading blockchain snapshot, show checksum which was verified, or add the description to reflect that downloaded snapshot is verified against checksum.

**Comment by ManuGowda** [comment]
## Comments from Rishi:

account:create command
```
1. After taking the passphrase input the cursor has a wrong position
2. --help description can be better
```

block:get
`Wrong error message when block height does not exist`

blockchain:export
`Wrong error message when output/input directory not found`

**Comment by Incede** [comment]
> `--enable-forger` which is for enabling the forger plugin should be renamed as it could be confused as a flag for enabling forging

**Comment by Incede** [comment]
passphrase:encrypt, passphrase:decrypt commands
```
1. Error message is wrong if password is not correct format
2. Warning message is wrong - should use "password", not "passphrase"
```

**Comment by ManuGowda** [comment]
Add period to root command if possible and make it uppercase `lisk-core help - display help for lisk-core`

**Comment by ManuGowda** [comment]
Consult `lisk-core warranty` command to be renamed to `disclaimer`
