### ISSUE TITLE
Command sdk:link is broken when parent directory is provided

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#407]
### Expected behavior

- Given parent directory `../` or home directory `~`, the `sdk:link` command must resolve the path correctly to link the SDK.

### Actual behavior

The `./bin/run sdk:link ../lisk-sdk/sdk` is broken

### Steps to reproduce

- Build lisk-sdk and follow procedure to link sdk
- Navigate to lisk-core and run `./bin/run sdk:link ../lisk-sdk/sdk`
- Run `npm run build` in lisk-core 
- The build fails

### Which version(s) does this affect? (Environment, OS, etc...)
development, 3.0.0

**Comment by nazarhussain** [comment]
It fixed the relative path but it broke the absolute path case.
