### ISSUE TITLE
Wrong return value in legacy account module

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-core#421]
### Expected behavior

Errors are returned correctly

### Actual behavior

`getUnregisteredAccount` returns `undefined` when the public key does not match any legacy address which causes the action to fail to resolve. It needs to wrap the error correctly. 
 
### Steps to reproduce

Once https://github.com/LiskHQ/lisk-core/issues/419 is fixed; try to get a legacy address with an invalid public key.
If you debug the result you'll get 

```
{
  jsonrpc: '2.0',
  id: null,
  error: {
    message: 'Internal error',
    code: -32603,
    data: 'Response must be sent with result or error'
  }
}
```

### Additional information 

There was some discussion about supporting returning `undefined` in `framework/src/controller/action.ts` so check with the team when starting this issue.

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by shuse2** [comment]
Superseded by https://github.com/LiskHQ/lisk-sdk/pull/5985.
It know allows to return undefined.
