### ISSUE TITLE
fromTimestamp for http core transactions api should work

### ISSUE THREAD

**Issue by sacOO7** [LiskHQ/lisk-core#463]
### Expected behavior
- Should return a list of transactions for a given range of from and to timestamp.

### Actual behavior
- It returns an empty list of transactions
 
### Steps to reproduce
- Try https://node.lisk.io/api/transactions?toTimestamp=1609876621
- It returns a list of transactions

- When a query is made using fromTimestamp and toTimestamp, returns an empty list. It should return transactions for the last 1 year.

- https://node.lisk.io/api/transactions?fromTimestamp=1578340621&toTimestamp=1609876621

### Which version(s) does this affect? (Environment, OS, etc...)
Try it on the browser, the problem in latest version

**Comment by sachinsh76** [comment]
Anyone .. please reply

**Comment by sacOO7** [comment]
It seems configuration for epoch time is given here https://lisk.io/documentation/lisk-sdk/references/config.html. 
I will try it out and close the issue if it's working : )

**Comment by sacOO7** [comment]
Working as per the above doc, so closing the issue : )
