### ISSUE TITLE
HD wallet

### ISSUE THREAD

**Issue by magmel48** [LiskHQ/lisk-core#474]
### Description

Is there any way to create hierarchical deterministic wallet generation schema? Like described here: https://en.bitcoinwiki.org/wiki/Deterministic_wallet.

### Motivation

Some master public key can be used to generate new addresses to accept money using derivation and master private key can be stored on some cold storage to avoid data leaks.

### Acceptance Criteria

- there is ability to create seed from mnemonic
- there is ability to create master public and master private key
- there is ability to create new public key and new address for that using derivation from master public key
- there is ability to create new private key and public key from master private key and with the same index and same path of derivation the addresses will be the same

### Additional Information

There is HD features implemented for:

ETH (https://github.com/ethereumjs/ethereumjs-wallet#hd-wallet-api)
BTC (bitcoinjs/bitcoinjs-lib#1454 (comment))

**Comment by janhack** [comment]
Thanks for your suggestions. Regarding HD wallets in Lisk, note the following:

- Lisk Core and any blockchain created with the Lisk SDK only handle public keys, signatures and addresses derived from the public keys are relevant and the protocol is not aware of how the key pairs are derived. This means that anyone could also develop an HD wallet for Lisk. 
- Our official wallets Lisk Desktop and Lisk Mobile do not use HD key derivation. One reason for that is that Lisk is an account-based blockchain (as opposed to a UTXO-based blockchains such as Bitcoin) so users typically use only one main address from which they vote, register multisignatures and perform other actions in the blockchain. To prevent account spamming we also introduce a minimum balance required for accounts (see [LIP 25](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0025.md)), which would make permanently changing accounts expensive.
- I have not used any third-party wallets for Lisk so maybe some of those support HD key derivation. As far as I know some hardware wallets also use HD key derivation so you may get this feature when using a hardware wallet. I would recommend to ask in our [Dev Forum](https://dev.lisk.io/) or on [Lisk Chat](https://lisk.chat/) as there are probably many community members which have experiences with different types of wallets.
