### ISSUE TITLE
globby is required by oclif

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-core#487]
### Expected behavior

`./bin/run` should run after `npm ci --production`

### Actual behavior

Fails with missing `globby` package.
`globby` is required by `oclif` and therefore is a `dependencies` and not a `devDependencies`.

### Steps to reproduce

```bash
npm run build && npm ci --production && ./bin/run start --network betanet
```

### Which version(s) does this affect? (Environment, OS, etc...)

At least `3.0.0-beta5`up to the head of `developement`

**Comment by shuse2** [comment]
to run with `./bin/run start` it should not use the `--production`.
If you want to run the without creating the binary, you can simply do
```
npm ci
./bin/run start --network betanet
```
or if you want to build binary
```
npm ci
npm run build
oclif-dev pack --targets=linux-x64
```

**Comment by JesusTheHun** [comment]
I figured it out, my goal was to build a docker image of lisk-core from the sources.
So yes, binaries. This is something every chain builder will want to do at some point. So I'm unsure about where it belongs, in the readme or in the doc on lisk.io ?

**Comment by shuse2** [comment]
good point, I think it should be written in the README.

**Comment by shuse2** [comment]
Closing this in favour  of https://github.com/LiskHQ/lisk-core/issues/491
