### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-core#491]
### Description

- General review of README file, outdated or missing documentation
  - README should explain how to build lisk core from source code from the `main` branch.
  - Update command `git checkout master` to `git checkout main`
  - README should also contain information about the following topics:
    - System requirements
    - Security best practices
    - Scalability options
    - (?) Specify the computation for the end of round block height
- Update installation steps to run `lisk-core` using `pm2`
  - Explain the pm2 deploy steps with/without `key` property

### Which version(s) does this affect? (Environment, OS, etc...)
4.0.0-

**Comment by ManuGowda** [comment]
@shuse2 some of the points would be difficult to update for now as these points are not answered yet

- System requirements
- Security best practices
- Scalability options
