### ISSUE TITLE
Update lisk core command to accept --api-ws-host

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#517]
### Description

- Update `lisk-core` to accept `--api-ws-host` flag to be able to configure the host.
- Add env variable for `--api-ws-host` to be used in docker
- Update README with the new env variable and flag

### Motivation

In order for other services to access Lisk Core along with port we need to provide the ability to also configure the host.

### Additional Information
- Currently we do not have any flags available to configure the host, and the default `rpc` host is set to `127.0.0.1` and when we run Lisk Core as container along side Lisk Service, the host is not anymore accessible at `127.0.0.1`.

**Comment by Gr33nDrag0n69** [comment]
Also please consider the exact same issue for the host of http-api now binding only on 127.0.0.1
i.e.: `--http-api-plugin-host`

**Comment by Gr33nDrag0n69** [comment]
same for the env var too

**Comment by Gr33nDrag0n69** [comment]
make sure to put in your backlog the update of this : https://lisk.com/documentation/lisk-sdk/guides/app-development/setup.html
