### ISSUE TITLE
transaction encoding

### ISSUE THREAD

**Issue by roccomuso** [LiskHQ/lisk-core#531]
### Description

Any documentation around explaining how txs are encoded?

**Comment by shuse2** [comment]
Lisk Core and Lisk SDK uses `lisk-corec` to encode/decode transaction object, and `lisk-codec` uses modified JSON Schema to define how each property should be encoded/decoded as explained https://lisk.com/documentation/lisk-sdk/advanced-explanations/schemas.html.

There is example here how it can be encode and signed.
 https://lisk.com/documentation/lisk-sdk/guides/node-management/signing-transactions-offline.html#require-the-transaction-and-asset-schema
