### ISSUE TITLE
disableDappTransaction does not work as expected

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#54]
### Expected behavior
`disableDappTransaction` should accept dApp transactions until a certain height.
### Actual behavior
`disableDappTransaction` does not accept dApp transactions until a certain height.
### Steps to reproduce
```
{
  "modules": {
    "network": {
      "seedPeers": [
        {
          "ip": "127.0.0.1",
          "wsPort": 5000
        }
      ]
    },
    "http_api": {
      "access": {
        "whiteList": [
          "127.0.0.1",
          "62.23.239.233"
        ]
      },
      "forging": {
        "access": {
          "whiteList": [
            "127.0.0.1",
            "62.23.239.233"
          ]
        }
      }
    },
    "chain": {
      "exceptions": {
        "precedent": {
          "disableDappTransfer": 10000
        }
      }
    }
  }
}
```
set `disableDappTransaction` to a certain height and send dApp registration, you will not be able to register dapp transaction.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by limiaspasdaniel** [comment]
After checking this along with @ManuGowda again, confirmed that indeed it works as expected. No further work to be done on this.

Check: https://github.com/LiskHQ/lisk-core/issues/19

**Comment by ManuGowda** [comment]
This issue is invalid for syncing, however, blockchain verification failed due to error in DApp disable https://github.com/LiskHQ/lisk-sdk/issues/3668
