### ISSUE TITLE
Reclaim transaction does not work

### ISSUE THREAD

**Issue by dakk** [LiskHQ/lisk-core#546]
I'm trying to create and broadcast a reclaim transaction (module 1000 asset 0), but 

### Expected behavior
I expect no errors

### Actual behavior

When I try to broadcast it with transaction:send lisk-core command, I get:

```
Error: Specified key accounts:address:XXX does not exist
```

where XXX is the address derived from the legacy pubkey I provided in the transcation.

### Steps to reproduce

I'm creating the transaction using liskhq/cryptography / liskhq/transaction; schema is like this:

```typescript
        const unsignedTransaction = {
            moduleID: 1000,
            assetID: 0,
            nonce: BigInt(1),
            fee: BigInt(fee),
            senderPublicKey: publicKey,
            asset: {
                amount: BigInt(account.balance), // - fee),
            }
        };
```

I think that lisk-core is checking if senderPublicKey correspond to a valid address, but it doesn't since it is a legacy account.

### Which version(s) does this affect? (Environment, OS, etc...)
Debian 10, lisk-core 3.0.0, mainnet

**Comment by sameersubudhi** [comment]
@dakk

Could you please share the `account` object that is used in:
```
            asset: {
                amount: BigInt(account.balance), // - fee),
            }
```

And, could you please share the `publicKey` of the account?

You can also check your eligible reclaim balance with `https://service.lisk.io/api/v2/accounts?publicKey=insert_your_publicKey_here` under `account.legacy.balance`, which is available iff the account is eligible for a reclaim.

**Comment by dakk** [comment]
> @dakk
> 
> Could you please share the `account` object that is used in:
> 
> ```
>             asset: {
>                 amount: BigInt(account.balance), // - fee),
>             }
> ```
> 
> And, could you please share the `publicKey` of the account?
> 
> You can also check your eligible reclaim balance with `https://service.lisk.io/api/v2/accounts?publicKey=insert_your_publicKey_here` under `account.legacy.balance`, which is available iff the account is eligible for a reclaim.

I've figured out the issue I was facing thanks to hirish: I need to put some beddows on the account (the lsk32 one) in order to send a valid reclaim transaction. Maybe docs need some words about it.

Please don't ask for users' addresses or pubkeys, is not very polite in the blockchain world.
