### ISSUE TITLE
Cannot use on Node.js 14.x LTS

### ISSUE THREAD

**Issue by magmel48** [LiskHQ/lisk-core#565]
### Expected behavior
Can be installed on env with Node.js 14.18.1 (LTS)

### Actual behavior
Need to use additional flags like `--ignore-engines` for yarn.

### Steps to reproduce
1. Install Node.js 14.x
2. Add the lib@5.2.0 as dependency in package.json
3. Run `yarn` or `npm i`

### Which version(s) does this affect? (Environment, OS, etc...)
All versions.

Most of the library functionality can be used also on 14.18.1. Why so strong restriction on only outdated Node.js 12.x? I think the strategy of using engines in package.json should be re-considered.

**Comment by sameersubudhi** [comment]
The issue is not relevant anymore. Lisk Core currently already supports the latest NodeJS LTS (`^16.14.2`).
