### ISSUE TITLE
Upgrade to non-vulnerable version of deep-extend

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-core#59]
### Expected behavior

There is no high severity security issue in `package-lock.json`.

### Actual behavior

> 1 deep-extend vulnerability found in package-lock.json 6 days ago

### Steps to reproduce

Look at https://github.com/LiskHQ/lisk-core/network/alert/package-lock.json/deep-extend/open

### Which version(s) does this affect? (Environment, OS, etc...)

`2.0`

**Comment by fchavant** [comment]
The security risk is rate "high" but nothing happened in 3 weeks @shuse2; is there a tag I should use?
Also there is now another high severity issue: https://github.com/LiskHQ/lisk-core/network/alert/package-lock.json/axios/open

**Comment by shuse2** [comment]
This is due to `swagger` related library, specific to `sway`.
There is no newer version right now

**Comment by shuse2** [comment]
This is solved indirectly by lisk-sdk v5 since it no longer uses swagger runner
