### ISSUE TITLE
Resolve todos

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-core#608]
### Expected behavior

The todo comments should be resolved.

### Actual behavior

We have 1 outstanding todo https://github.com/LiskHQ/lisk-core/search?q=todo

**Comment by sameersubudhi** [comment]
Reopened the issue since there are 3 more TODOs to be addressed in the following files:
- test/scripts/utils/transactions/send.ts
- test/scripts/utils/schemas.ts
- test/utils/transactions.ts

**Comment by ManuGowda** [comment]
> Reopened the issue since there are 3 more TODOs to be addressed in the following files:
> 
> * test/scripts/utils/transactions/send.ts
> * test/scripts/utils/schemas.ts
> * test/utils/transactions.ts

Updated this https://github.com/LiskHQ/lisk-core/issues/694 with those todos, so we can close this.

i will address them in that issue.
