### ISSUE TITLE
Update default LISK_PORT value

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-core#611]
### Description

Change the default `port (LISK_PORT)` value from `5000`. Lisk Core uses it for the peer to peer incoming connections.

### Motivation

With macOS Monterey (version 12), the OS now uses the port `5000` for its `AirPlay Receiver` functionality. This forces the users to specify an additional custom port.

### Additional information

Based on current decision we can go `7667` with https://github.com/LiskHQ/lisk-sdk/issues/6361

**Comment by ManuGowda** [comment]
Further changes are expected in this issue https://github.com/LiskHQ/lisk-sdk/issues/6361
