### ISSUE TITLE
Move tests related to Dapp Transactions to Lisk Core

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-core#64]
Dapp related Transactions are now part of Lisk Core only and can't be tested on the framework level because Jenkins starts the application using `framework/test/test_app/index.js` and it doesn't contain these transaction types.
They are currently skipped and should be moved to Lisk Core functional test.

Dapp related functional testes:
```
framework/test/mocha/functional/http/post/5.dapps.js
framework/test/mocha/functional/http/post/6.dapps.in_transfer.js
framework/test/mocha/functional/http/post/7.dapps.out_transfer.js
```

### Which version(s) does this affect? (Environment, OS, etc...)
2.0

**Comment by shuse2** [comment]
Closing the issue because it would not be required with the migration plan
