### ISSUE TITLE
node version 10.15.3 - hard requirement

### ISSUE THREAD

**Issue by magick93** [LiskHQ/lisk-core#79]
Hello

I'm wondering why there is a hard requirement on a specific version of node, being 10.15.3, rather than a major version or LTS release?

### Which version(s) does this affect? (Environment, OS, etc...)

Linux

**Comment by shuse2** [comment]
We are constantly updating the node.js version to the latest LTS.
Because we cannot guarantee the behavior on the other version, It is hard requirement now.

**Comment by magick93** [comment]
So when will you use LTS, rather than 10.15.3? 

10.15.3 is not a LTS release.

**Comment by magick93** [comment]
> We are constantly updating the node.js version to the latest LTS.


Can this issue please be re-opened so that I can be notified when you are using an LTS version.

I'm working in an environment where I cannot build unless node is a LTS version, and `10.15.3` is not LTS.
