### ISSUE TITLE
Can I create my own blockchain based on Lisk?

### ISSUE THREAD

**Issue by EtherForge** [LiskHQ/lisk-core#827]
Hello! I want to know if I can make my own cryptocurrency based on yours, observing all licensing rules. As far as I know, many projects have a command that allows you to simply change the name of the blockchain. Is it possible to do the same with yours?

**Comment by przemerr** [comment]
Yes, you can create a custom blockchain using lisk-commander/lisk-sdk https://lisk.com/documentation/beta/build-blockchain/index.html

also there's a grant program currently running http://accelerator.lisk.com/
you can get funding up to $250k for your project.

**Comment by sameersubudhi** [comment]
@EtherForge Thank you for the query. Please check the documentation shared by @przemerr above. For more information or clarifications please connect with us and our community members on https://lisk.chat.
