### ISSUE TITLE
Show version in pm2

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-core#903]
Currently pm2 is not able to show the version of Lisk Core. This can be helpful, so please add it.

![image](https://github.com/LiskHQ/lisk-core/assets/1260700/51abf35c-4e77-442a-a5b7-6ebb19e8c3a9)

**Comment by sameersubudhi** [comment]
The version is automatically picked by pm2 from the package.json and we cannot manually enforce a display version within the pm2 config file.

Closing the issue.
