### ISSUE TITLE
Docker containers die after Docker service restarts

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-core#98]
### Expected behavior

If the Docker daemon restarts due to an upgrade or any other reason, the Docker containers from our application should keep running.

### Actual behavior

After an upgrade or a random restart of the Docker daemon, Docker containers from our application don't restart properly affecting the working of our application.

### Steps to reproduce

- `docker ps` check if the containers are running properly
- Restart Docker service
- `docker ps` and check if the same containers are running properly

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0+`

**Comment by fchavant** [comment]
This is related to https://github.com/LiskHQ/lisk-docs/issues/291
